sudo: false
dist: xenial
language: php


before_install:
  - if php --ri xdebug >/dev/null; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - |
    wget -O phive.phar https://phar.io/releases/phive.phar && \
    wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc && \
    gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79 && \
    gpg --verify phive.phar.asc phive.phar && \
    chmod +x phive.phar

install:
  - travis_retry composer install --no-interaction
  - travis_retry ./phive.phar install --no-interaction --force-accept-unsigned --trust-gpg-keys 8E730BA25823D8B5


php:
  - 7.1
  - 7.2
  - 7.3

script: composer test


jobs:
  include:
    - stage: QA
      name: Code Coverage
      php: 7.3
      script: composer cover
      after_success: bash <(curl --retry 3 -s https://codecov.io/bash)

    - stage: QA
      name: Lint
      php: 7.3
      script: composer lint

    - stage: QA
      name: Static Analysis
      php: 7.3
      script: composer analyze

    - stage: QA
      name: Code Style
      php: 7.3
      script: composer stylist

    - stage: QA
      name: Internal Dependencies
      php: 7.3
      script: composer deptrac

    - stage: Deploy
      name: Deploy
      php: 7.3
      script: composer build

      before_deploy:
        - echo "$ENCRYPTION_PASSPHRASE" | gpg --passphrase-fd 0 build/keys.asc.gpg
        - gpg --batch --yes --import build/keys.asc
        - echo "$SIGNING_KEY_PASSPHRASE" | gpg --passphrase-fd 0 --local-user B352BC4C --armor --detach-sig bin/stylist.phar

      deploy:
        provider: releases
        api_key: $GITHUB_API_TOKEN
        skip_cleanup: true
        file:
          - bin/stylist.phar
          - bin/stylist.phar.asc
        on:
          tags: true
          repo: php-stylist/Stylist

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
